language: cpp

matrix:
  include:
    # Clang
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-9
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # Clang Exceptions + RTTI
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-9
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DRST_ENABLE_CXX_EXCEPTIONS=ON -DRST_ENABLE_CXX_RTTI=ON -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # Clang ASAN
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-9
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DRST_ENABLE_ASAN=ON -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # Clang TSAN
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-9
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DRST_ENABLE_TSAN=ON -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # Clang UBSAN
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-9
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DRST_ENABLE_UBSAN=ON -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # Clang Release
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - clang-9
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release

      script: ninja

    # GCC
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-8
            - gcc-8
            - ninja-build
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # GCC Exceptions + RTTI
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-8
            - gcc-8
            - ninja-build
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DRST_ENABLE_CXX_EXCEPTIONS=ON -DRST_ENABLE_CXX_RTTI=ON -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # GCC Release
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - g++-8
            - gcc-8
            - ninja-build
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release

      script: ninja

    # OS X Clang
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - ninja
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # OS X Clang Exceptions + RTTI
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - ninja
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DRST_ENABLE_CXX_EXCEPTIONS=ON -DRST_ENABLE_CXX_RTTI=ON -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # OS X Clang Release
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - ninja
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release

      script: ninja

    # OS X GCC
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - gcc@8
            - ninja
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # OS X GCC Exceptions + RTTI
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - gcc@8
            - ninja
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DRST_ENABLE_CXX_EXCEPTIONS=ON -DRST_ENABLE_CXX_RTTI=ON -DCMAKE_BUILD_TYPE=Debug

      script: ninja && ./rst_tests

    # OS X GCC Release
    - os: osx
      osx_image: xcode11.3
      addons:
        homebrew:
          update: true
          packages:
            - gcc@8
            - ninja
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

      before_install:
          - eval "${MATRIX_EVAL}"

      before_script:
        - mkdir build
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release

      script: ninja

    # MSVC 2017 Win32
    - os: windows
      before_script:
        - mkdir build
        - cd build
        - cmake .. -G"Visual Studio 15 2017"

      script: cmake --build . && ./Debug/rst_tests.exe

    # MSVC 2017 Win32 Release
    - os: windows
      before_script:
        - mkdir build
        - cd build
        - cmake .. -G"Visual Studio 15 2017"

      script: cmake --build . --config Release

    # MSVC 2017 Win64
    - os: windows
      before_script:
        - mkdir build
        - cd build
        - cmake .. -G"Visual Studio 15 2017 Win64"

      script: cmake --build . && ./Debug/rst_tests.exe

    # MSVC 2017 Win64 Release
    - os: windows
      before_script:
        - mkdir build
        - cd build
        - cmake .. -G"Visual Studio 15 2017 Win64"

      script: cmake --build . --config Release

    # MSVC 2019 Win32
    - os: windows
      before_script:
        - choco install visualstudio2019buildtools
        - choco install visualstudio2019-workload-vctools
        - mkdir build
        - cd build
        - cmake .. -G"Visual Studio 16 2019" -A Win32

      script: cmake --build . && ./Debug/rst_tests.exe

    # MSVC 2019 Win32 Release
    - os: windows
      before_script:
        - choco install visualstudio2019buildtools
        - choco install visualstudio2019-workload-vctools
        - mkdir build
        - cd build
        - cmake .. -G"Visual Studio 16 2019" -A Win32

      script: cmake --build . --config Release

    # MSVC 2019 Win64
    - os: windows
      before_script:
        - choco install visualstudio2019buildtools
        - choco install visualstudio2019-workload-vctools
        - mkdir build
        - cd build
        - cmake .. -G"Visual Studio 16 2019" -A x64

      script: cmake --build . && ./Debug/rst_tests.exe

    # MSVC 2019 Win64 Release
    - os: windows
      before_script:
        - choco install visualstudio2019buildtools
        - choco install visualstudio2019-workload-vctools
        - mkdir build
        - cd build
        - cmake .. -G"Visual Studio 16 2019" -A x64

      script: cmake --build . --config Release
